In [25]:
import numpy as np
import pandas as pd
from transformers import RobertaTokenizerFast, RobertaModel, AdamW, get_linear_schedule_with_warmup
from sklearn.metrics import mean_squared_error as mse
from sklearn.model_selection import train_test_split
import tqdm

In [21]:
data = pd.read_csv("../dataset/data.csv")
data.head()

sentiment                                         clean_text
0        0.0             aaplthe 10 best steve jobs emails ever
1        0.0  rt why aapl stock had a miniflash crash today ...
2        0.0          my cat only chews cords such an applesnob
3        0.0  i agree with that the individualinvestor shoul...
4        0.0        nobody expects the spanish inquisition aapl

In [22]:
data_train, data_val, y_err_train, y_err_val = train_test_split(
                                                        data['clean_text'].values, 
                                                        data['sentiment'].values,
                                                        test_size=0.15,
                                                        random_state=42)
print(data_train.shape, data_val.shape)

(5622,) (993,)


In [26]:
tokenizer = RobertaTokenizerFast.from_pretrained('roberta-base')

In [31]:
for dt in data_train:
    encoded_data_train = tokenizer.encode_plus(
        dt,
        add_special_tokens=True,
        max_length=512,
        return_tensors='tf',
    )
    print(encoded_data_train)

# encoded_data_val = tokenizer.encode_plus(
#     data_val,
#     add_special_tokens=True,
#     return_attention_mask=True,
#     pad_to_max_length=True,
#     max_length=512,
#     return_tensors='pt'
# )

# input_ids_train = encoded_data_train['input_ids']
# attention_masks_train = encoded_data_train['attention_mask']
# values_train = torch.tensor(y_err_train[:, 0],dtype=torch.float)
# errors_train = torch.tensor(y_err_train[:, 1],dtype=torch.float)

# input_ids_val = encoded_data_val['input_ids']
# attention_masks_val = encoded_data_val['attention_mask']
# values_val = torch.tensor(y_err_val[:, 0], dtype=torch.float)
# errors_val = torch.tensor(y_err_val[:, 1],dtype=torch.float)

{'input_ids': <tf.Tensor: shape=(1, 19), dtype=int32, numpy=
array([[    0,   405,  1364,   456, 26536,   254,    45,   145,    10,
         1368,  3540,   114,    63,   129,    65,   621,  5278,   417,
            2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 19), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
      dtype=int32)>}
{'input_ids': <tf.Tensor: shape=(1, 26), dtype=int32, numpy=
array([[    0,  9713,  4800,  1289,  1597,   179,  3246,    11,  1400,
           11,   295,   219,   438,    16,    24,   162,    50,    16,
           42,  6378, 33540, 24352,   114,    47,  2854,     2]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 26), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1]], dtype=int32)>}
{'input_ids': <tf.Tensor: shape=(1, 17), dtype=int32, numpy=
array([[    0, 39563,    13,   489, 13964,    77, 19116,  6773,    31,
           10,

TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]